name: lumora_core
description: Core schema interpretation and rendering engine for Lumora framework. Enables real-time UI rendering from JSON schemas.
version: 0.1.0-alpha.1
homepage: https://github.com/lumora/lumora
repository: https://github.com/lumora/lumora
issue_tracker: https://github.com/lumora/lumora/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Design tokens
  lumora_ui_tokens:
    path: ../lumora_ui_tokens

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
